### ISSUE TITLE
show plugin names in user warnings

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/osbs-client#1027]
Thanks for the new user warnings feature.

It would be nice to show the plugin that provided the warning.

For example, it took me a while to discover what a single warning `Inheritance is not allowed for scratch or isolated builds. Skipping inheritance.` means. The term "inheritance" can mean a couple different things in the build system.

When I read the Koji task's `orchestrator.log`, it's clearer:
```
2021-06-16 08:50:41,105 platform:- - atomic_reactor.plugins.resolve_composes - INFO - Inheritance requested in config file
2021-06-16 08:50:41,105 platform:- - atomic_reactor.plugins.resolve_composes - WARNING - Inheritance is not allowed for scratch or isolated builds. Skipping inheritance.
```

It turns out that it means this user has set `inherit: true` within the `compose` key in the `container.yaml` file in dist-git. `orchestrator.log` shows the plugin name clue that we're talking about *composes*, but `user_warnings` does not.

If we displayed OSBS's `pre_resolve_composes` plugin name there, the warning messages would be clearer to users. It would be easier for users to become contributors, because they could find this code more easily and improve the error message texts.

**Comment by MartinBasti** [comment]
Hello,
thank you very much for the report. You are right

My feeling is that this is issue with the text of the user warning. We shouldn't expect users to have knowledge of which plugins do what. We should write nice descriptive and clear error messages instead.

CC @ssalatsk

**Comment by lcarva** [comment]
Going a step further, it would be nice if users didn't have to be aware of plugins at all. The message could be written in a way that makes sense to the user without having to know which plugin it came from, for example: `inherit: true in the compose section of container.yaml is not allowed for scratch or isolated builds. Ignoring this value.`

**Comment by ktdreyer** [comment]
Sure, an OSBS developer could fix that particular warning message to be clearer.

Doing that across the entire codebase for every warning is a lot of up-front work. The reason I suggested adding the plugin names is that sometimes it's not trivial to improve the messages.

To borrow another example,

```python
try:
    os.remove(operator_manifests_path)
except OSError as e:
    self.log.warning("Cleanup of the downloaded archive failed: %s", e)
```
When we log the plugin name, it's clearer what "downloaded archive" means.

If we provided the plugin names, users can type their error message into a search engine and we increase the odds that they end up in the right place (reading the source code). It's a bit like Apache's "AH" error codes.

**Comment by lcarva** [comment]
@ktdreyer, "user warnings" are different than self.log.warning. They are created by a call to `self.log.user_warning`.  These are the warnings that propagated back to the user via the koji task. The other ones stay buried in the logs. I don't know exactly why we have two types of warnings though. My guess is that we didn't want to rewrite all the ~75 calls to `self.log.warning`. There are only three calls to `self.log.user_warning` so it seems quite reasonable to rewrite those.

**Comment by MartinBasti** [comment]
we have `log.user_warning` to provide only meaningful warnings to users. We don't want to spam users with some OSBS system warnings, it may be too much an not relevant for users.

**Comment by MartinBasti** [comment]
I updated warning message here, https://github.com/containerbuildsystem/atomic-reactor/pull/1638 

Do you agree with such resolution of this issue?

**Comment by ktdreyer** [comment]
Ok, thanks for explaining this. I missed that `warning()` is separate from `user_warning()`. That atomic-reactor PR is ok for this error.
