### ISSUE TITLE
Flexmock now has a module with exceptions

### ISSUE THREAD

**Issue by frenzymadness** [containerbuildsystem/osbs-client#1055]
The tests are failing with the latest flexmock because of line:

https://github.com/containerbuildsystem/osbs-client/blob/1b5823ec62be281cea8e096a034997ff86cdab86/tests/test_api.py#L11

should now be: 
```python
from flexmock import flexmock
from flexmock.exceptions import MethodCallError
```
See https://github.com/flexmock/flexmock/blob/master/CHANGELOG.md#release-0110

**Comment by frenzymadness** [comment]
Fixed in the linked PR.

**Comment by MartinBasti** [comment]
Thank you for reporting this
